# normal relaunch, kills the pid
# guard :relaunch, command: "rackup -p 3000", watch: /\.rb/

# custom relaunch, define a kill command
guard :relaunch, watch: /\.rb/, command: "rackup -p 3000"#, kill_command: "sudo killall -9 rackup"