# normal relaunch, kills the pid
# guard :relaunch, command: "rackup -p 3000", watch: /\.rb/

# custom relaunch, define a kill command
# osx
#guard :relaunch, command: "rackup -p 3000", kill_command: "sudo killall -9 rackup", watch: /\.rb/

# linux
guard :relaunch, command: "rackup -p 3000", watch: /\.rb/